#!/bin/sh
f=5
while [ $f -gt 0 ]
do
   if [ -f "build.sh" ]; then
      ./build.sh $*
      f=-1
	 elif [ -f "makefile" ]; then
	    make $*
	    f=-1
   else
      cd ../
      f=$(echo "$f-1" | bc)
   fi
done
