#!/bin/sh
f=5
while [ $f -gt 0 ]
do
   if [ -f "./build.sh" ]; then
      ./build.sh
      f=0
	elif [ -f "./Makefile" ]; then
		make
		f=0
   else
      cd ../
      f=$(echo "$f-1" | bc)
   fi
done
