#!/bin/sh

FILE="/home/eliasnijs/System/scripts/.storage/logbook"
CURRENTDATE=`date +"%Y-%m-%d %T"`

if [ ! -f "$FILE" ]; then
	echo "AssertionError: file not found"
   exit 2
fi

while getopts ":a:ls::" opt; do
    case $opt in
      a) add=true
         title="${OPTARG}"
	      ;;
      l) list=true
	      ;;
	   s) search=true
	      query="${OPTARG}"
	      ;;
	   \?) echo "AssertionError: wrong syntax" 1>&2
          exit 1;
    esac
done
shift $((OPTIND-1))

addfunction() {
	echo $CURRENTDATE
	echo "\033[53;1mENTER LOG\e[0m";
	read text
	line="$1 - $CURRENTDATE - $text"
	echo "$line" >> $FILE
	echo "\033[53;1mADDED:\e[0m $line"
}

searchfunction() {
	echo "\033[53;1mLINES FOUND($(grep "$query" $FILE | wc -l))\e[0m";
	grep "$query" $FILE
}

listfunction() {
	echo "\033[53;1mLOGS($(cat $FILE | wc -l))\e[0m";
	cat $FILE
}

if [ $add ]; then
	addfunction $title
elif [ $remove ]; then
	removefunction
elif [ $search ]; then
	searchfunction
elif [ $list ]; then
	listfunction
fi

