#!/bin/sh

ls -l
echo " " 
file=$(find . -maxdepth 1 -name "README*")
if test $file; then
	# catmd $file | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' | head -n 12
	catmd $file
	# if [ "$(wc -l $file | cut -d " " -f 1)" -ge "12" ]; then
  #   echo ...
	# fi
fi


