#!/bin/sh
f=3
while [ $f -gt 0 ]
do
   if [ -f "./run.sh" ]; then
      ./run.sh $*
      f=0
	elif [ -f "./Makefile" ]; then
		make test $*
		f=0
   else
      cd ../
      f=$(echo "$f-1" | bc)
   fi
done
