#!/bin/sh

f=5
while [ $f -gt 0 ]
do
   if [ -f "test.sh" ]; then
      ./test.sh $*
      f=-1
   elif [ -f "scripts/test.sh" ]; then
      cd scripts/
      ./test.sh $*
      f=-1
   elif [ -f "makefile" ]; then
      make test $*
      f=-1
   else
      cd ../
      f=$(echo "$f-1" | bc)
   fi
done
