#!/bin/sh

FILE_NAME=$(echo "screenshot$(date +"%F%T.%2N").png")
SAVE=1
COPY_PASTE=0

while getopts "cn:" opt
do
   case "${opt}" in
      c) COPY_PASTE=1
         SAVE=$(echo $SAVE - 1 | bc)
         ;;
      n) FILE_NAME="${OPTARG}"
         case "$FILE_NAME" in
            *".png")
               ;;
            *)
               FILE_NAME="$FILE_NAME.png"
               ;;
         esac
         SAVE=2
         ;;
      \?) exit 1
          ;;
   esac
done
shift $((OPTIND-1))
echo $SAVE $COPY_PASTE
if test -f "$FILE_NAME"; then
   echo "file already exists! quitting program..."
   exit 1
fi
import "./$FILE_NAME"
if [ $COPY_PASTE -eq 1 ]; then
   xclip -selection clipboard -t image/png -i $FILE_NAME 
fi
if [ $SAVE -eq 0 ]; then
   rm "./$FILE_NAME"
fi

