#!/bin/sh

CONFIGLOC="/home/eliasnijs/System/scripts/.config"
STORAGELOC="/home/eliasnijs/System/scripts/.storage"
SUNSET="18"

wallpaper

exec slstatus

echo "$(date +"%Y-%M-%d %T")     IN" >> "$STORAGELOC/logtimes"

stock-update

screen-secondmonitor

dark=0
if [ "$(date +%H)" -gt $SUNSET"" ]; then
   dark=1;
fi
echo "$dark" > "$CONFIGLOC/nightmode"


