#!/bin/sh

path_config=$(echo $(dirname $(readlink -f $0))/.storage)
path_storage=$(echo $(dirname $(readlink -f $0))/.config)

exec slstatus & 

echo "$(date +"%F %T")     IN" >> "$path_storage/logtimes"
screen-secondmonitor
wallpaper
stock-update 
setxkbmap -option caps:swapescape
