#!/usr/bin/python3

import sys
import yfinance as yf

if len(sys.argv) < 2:
    print('Usage: stock-value <ticker>')
    sys.exit(1)

for ticker in sys.argv[1:]:
    stock_data = yf.Ticker(ticker).history(period='1d')
    if stock_data.empty:
        print(f'No data available for {ticker}')
        continue

    value         = stock_data['Close'].iloc[-1]
    opening_price = stock_data['Open'].iloc[-1]
    daychange     = value - opening_price

    print(f'{ticker:8} {value:8.2f} ({daychange:8.2f}%)')
