#!/bin/sh

cd $(dirname $(readlink -f $0))
symbol=$(cat .storage/emojis.txt .storage/math.txt | dmenu | grep -o "^[^ ]*")
echo -n $symbol | xclip -selection clipboard
echo -n $symbol | xclip -selection primary


