#!/bin/sh

if [ ! -z $1 ]; then
  p=$(ps -ef | grep $1 | fzf | awk '{print $2}')
  if [ "$(echo $p | wc -c)" -gt "1" ]; then
    kill $p
  else 
    echo no process was chosen!
  fi
else
  echo no argument provided!
fi

