#!/usr/bin/env python3

import sys
import os

path = os.path.realpath(__file__).rstrip("todo") + ".storage/todo"

items = []
for x in open(path):
    items.append(x.strip())

args = sys.argv[1:]

if len(args) <= 1:
    t = 1
    for x in items:
        print(f"{t}. {x}")
        t += 1
else:
    opt = args[0]
    item = " ".join(args[1:])
    if not (opt == 'a' or opt == 'r'):
        print("invalid option")
        sys.exit()
    if opt == 'a':
        items.append(item)
    if opt == 'r':
        if not item.isdigit():
            print("invalid index")
            sys.exit()
        index = int(item) - 1
        if not (0 <= index < len(items)):
            print("invalid index")
            sys.exit()
        items.pop(index)

    items = "\n".join(items)
    f = open(path,"w")
    f.write(items)
    f.close()
