#!/bin/bash

current_loc=$(pwd)
script_loc=$(dirname $(readlink -f $0))
cd $script_loc 
wallpaperfolder="../configuration/wallpapers/"
wallpaper_loc="../configuration/wallpapers/wallpaper.png"

add=0
file=""
random=0
folder="$wallpaperfolder"
setwallpaper=0
wallpaper=""

while getopts ":a:rfs:" opt
do
   case "${opt}" in
      a)
         add=1
         file="${OPTARG}"
         ;;
      r)
         random=1
         ;;
      f)
         random=1
         folder=$current_loc
         ;;
      s)
         setwallpaper=1
         wallpaper="${OPTARG}"
         ;;
      \?) 
         echo "AssertionError: invalid options"
         exit 1
         ;;
   esac
done
shift $((OPTIND-1))

if [ "$add" -eq "1" ]; then
   cp $file $wallpaperfolder 
fi

if [ "$random" -eq "1" ]; then
   files=$(find $folder -name '*' -exec file {} \; | grep -o -P '^.+: \w+ image' | sed s/:.*image//)
   file=$(echo $files | cut -d " " -f $(echo $((1 + $RANDOM % $(echo $files | wc -w)))) | sed "s/ //g")   
   cp $file $wallpaper_loc 
fi

if [ "$setwallpaper" -eq "1" ]; then
	cp $wallpaper $wallpaper_loc 
fi

echo $wallpaper_loc

feh --bg-fill $wallpaper_loc
