#!/bin/sh

mpv --geometry=-0-0 --autofit=20% --demuxer-max-bytes=200000 --demuxer-max-back-bytes=24000000 --untimed /dev/video0 &
# mpv --geometry=-0-0 --autofit=20% --demuxer-max-bytes=75000 --demuxer-max-back-bytes=16000000 /dev/video0 &

