#!/bin/sh

cd $(dirname $(readlink -f $0))
path_config="../scripts/.config"
path_storage="../scripts/.storage"

exec slstatus &

screen-secondmonitor
wallpaper

exec picom &

setxkbmap -option caps:swapescape

stock-update 
echo "\"$(date +"%F %T")\",ON" >> "$path_storage/logtimes"
