#!/bin/sh

cd $(dirname $(readlink -f $0))
path_config="../scripts/.config"
path_storage="../scripts/.storage"

exec slstatus &

screen-secondmonitor
wallpaper

setxkbmap -option caps:swapescape

transparant

